version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 3
    groups:
      frontend-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

      frontend-major:
        patterns:
          - "*"
        update-types:
          - "major"

    labels:
      - "dependencies"

  - package-ecosystem: "nuget"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 3
    groups:
      backend-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    cooldown:
      default-days: 3
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
