<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>97caafb9-7384-4b70-9818-449a86a18dda</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SomnosSuite.Application\SomnosSuite.Application.csproj" />
    <ProjectReference Include="..\SomnosSuite.Infrastructure\SomnosSuite.Infrastructure.csproj" />
    <ProjectReference Include="..\SomnosSuite.Persistence\SomnosSuite.Persistence.csproj" />
    <ProjectReference Include="..\SomnosSuite.Presentation\SomnosSuite.Presentation.csproj" />
  </ItemGroup>

</Project>
